version: '2'

services:
  adapter:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "5600:5600"
    #links:
    #  - keycloak
    environment:
      - KEYCLOAK_ADDRESS=keycloak
      - KEYCLOAK_PORT=5601
      - KEYCLOAK_PATH=auth
      - SONATA_REALM=sonata
      - CLIENT_NAME=adapter
    container_name: son-gtkusr
  keycloak:
    build:
      context: ./
      dockerfile: Dockerfile-Keycloak
    ports:
      - "5601:5601"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    links:
      - adapter
    container_name: sonata-keycloak    
